### ISSUE TITLE
FileNotFoundError problem

### ISSUE THREAD

**Issue by wgh1992** [saisrivatsan/deep-opt-auctions#1]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-e69db71872fb> in <module>
      2 generator = Generator(cfg, 'test', X_tst)
      3 clip_op_lambda = (lambda x: tf.assign(x, tf.clip_by_value(x, 0.0, 1.0)))
----> 4 m = Trainer(cfg, "test", net, clip_op_lambda)
      5 m.test(generator)

D:\coding\jupyter workplace\deep-opt-auctions-master\regretNet\trainer\trainer.py in __init__(self, config, mode, net, clip_op_lambda)
     18 
     19         # Create output-dir
---> 20         if not os.path.exists(self.config.dir_name): os.mkdir(self.config.dir_name)
     21 
     22         if self.mode == "train":

FileNotFoundError: [WinError 3] : 'experiments\\additive_1x2_uniform'

 When I running the program, it shows can not find the file,
Then I change following sentence,

# Output-dir to write log-files and save model
__C.dir_name = os.path.join("experiments", "additive_1x2_uniform")

But it does not work.

**Comment by saisrivatsan** [comment]
You first need to train the model before you can run the test script. 
The train script stores the model at the required folder which is then used for testing. We, unfortunately, don't have pre-trained models yet that you can test on directly.
